# docker-compose.yml
# Usage: docker-compose up -d
version: "3.8"

networks:
  pixelcast_network:
    driver: bridge

services:
  srs:
    # Use the official SRS 6 image
    image: ossrs/srs:6

    # Container name for easier management
    container_name: srs-server

    # Restart the container automatically if it stops
    restart: unless-stopped

    # Mount the custom configuration file into the container
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf

    # Map the necessary ports from the host to the container
    ports:
      - "1935:1935" # RTMP
      - "1985:1985" # HTTP API
      - "8080:8080" # HTTP Server (for demos/players)
      - "8000:8000/udp" # WebRTC over UDP
      - "8001:8001/tcp" # WebRTC over TCP (Fallback)

    # Set the WebRTC candidate IP address
    # In a Docker environment, we can use the service name `srs` as the hostname
    environment:
      - CANDIDATE=srs
    networks:
      - pixelcast_network

  backend:
    build: .
    container_name: pixelcast-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - srs
    # You might want to use an .env file for environment variables
    # env_file:
    #   - .env
    environment:
      - SRS_SERVER_IP=srs
    networks:
      - pixelcast_network
