version: "3.8"

services:
  # SRS Media Server (Simple Realtime Server)
  srs:
    image: ossrs/srs:6
    container_name: srs-server
    ports:
      - "1935:1935" # RTMP
      - "1985:1985" # HTTP API
      - "8080:8080" # HTTP Server
      - "8000:8000/udp" # WebRTC
    environment:
      - CANDIDATE=192.168.0.107
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
    networks:
      - srs-network

networks:
  srs-network:
    driver: bridge
